In [1]:
from sklearn.neighbors import KNeighborsClassifier


In [2]:
model = KNeighborsClassifier()

In [3]:
y = [1,0,1,0,1,0,1,0,1,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1,1,0,1,0,1]


In [4]:
import pandas as pd


In [5]:
import seaborn as sns

In [38]:
boxe = sns.load_dataset('boxe')

In [39]:
sns.get_data_home()

'C:\\Users\\Leader\\seaborn-data'

In [40]:
boxe.shape


(999, 6)

In [41]:
boxe.head()

win  age  weight  Size  NbVictory  NbLose
0    1   24      85   188         20       0
1    0   40     110   165         11       9
2    1   30     100   190         35       4
3    0   28      60   160          8       6
4    1   19     100   187          7       7

In [42]:
y = boxe['win']

In [43]:
y.shape


(999,)

In [44]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: win, dtype: int64

In [45]:
x = boxe.drop('win', axis=1)

In [17]:
x


age  weight  Size  NbVictory  NbLose
0    24      85   188         20       0
1    40     110   165         11       9
2    30     100   190         35       4
3    28      60   160          8       6
4    19     100   187          7       7
5    18      90   185          3       1
6    22      91   188         37      34
7    38     110   184          9      16
8    26     100   213         12      20
9    28     105   217         28      35
10   29     120   158          8      38
11   45     102   200         43      29
12   45      71   182         19      46
13   44      89   201          6      45
14   23      77   164          8      15
15   28     122   156         15      12
16   31     113   198         28      18
17   32      90   176         11       6
18   41     122   171         34      11
19   29     114   201         16      30
20   42      74   198         35      49
21   21      84   218          5      18
22   19      67   161         27      22
23   47     104   164         29       3
24   18      66   176         47      11
25   54      94   200          6      25
26   41      76   170         49      49
27   25      75   215         41       0
28   21      64   176         21      46

In [46]:
model.fit(x, y)

KNeighborsClassifier()

In [47]:
model.score(x, y)

0.6786786786786787

In [20]:
model.predict(x)

array([1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [49]:
def win(model, age = 40, weight = 60, size = 160, NbVictory = 16, NbLose = 7):
    x = np.array([age, weight, size, NbVictory, NbLose]).reshape(1,5)
    print(model.predict(x))
    print(model.predict_proba(x))
    

In [25]:
import numpy as np

In [26]:
win(model)

[0]


In [27]:
win(model)

[0]


In [31]:
win(model)

[0]
[[0.6 0.4]]


In [33]:
win(model)

[1]
[[0.4 0.6]]


In [50]:
win(model)

[1]
[[0.4 0.6]]


In [52]:
import matplotlib.pyplot as plt

In [55]:
from sklearn.datasets import make_regression
from sklearn.linear_model import SGDRegressor 